version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - |
        cd Frontend
        npm install --legacy-peer-deps
  
  build:
    commands:
      - |
        cd Frontend
        npm run build
        ls -la dist/
  
  post_build:
    commands:
      - |
        cd Frontend
        
        if [ -z "$S3_BUCKET_NAME" ]; then
          echo "ERROR: S3_BUCKET_NAME not set"
          exit 1
        fi
        
        # 버전 정보
        BUILD_TIME=$(date +%Y%m%d-%H%M%S)
        COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
        
        echo "===== Creating Archive ====="
        cd dist
        zip -r ../dist-${BUILD_TIME}.zip .
        cd ..
        
        echo "===== Uploading to S3 ====="
        # 버전별 아카이브
        aws s3 cp dist-${BUILD_TIME}.zip s3://$S3_BUCKET_NAME/releases/dist-${BUILD_TIME}.zip
        
        # 최신 버전 (항상 덮어쓰기)
        aws s3 cp dist-${BUILD_TIME}.zip s3://$S3_BUCKET_NAME/dist-latest.zip
        
        echo "===== URLs ====="
        echo "Latest: https://$S3_BUCKET_NAME.s3.amazonaws.com/dist-latest.zip"
        echo "Version: https://$S3_BUCKET_NAME.s3.amazonaws.com/releases/dist-${BUILD_TIME}.zip"

cache:
  paths:
    - 'Frontend/node_modules/**/*'