version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - |
        echo "===== Environment Check ====="
        pwd
        ls -la
        echo ""
        echo "===== Moving to Frontend ====="
        cd Frontend || { echo "Failed to cd into Frontend"; exit 1; }
        pwd
        ls -la
        echo ""
        echo "===== Installing Dependencies ====="
        npm install --legacy-peer-deps
  
  build:
    commands:
      - |
        cd Frontend
        echo "===== Building Application ====="
        npm run build
        echo ""
        echo "===== Build Output ====="
        ls -la dist/
        echo "Total files: $(find dist -type f | wc -l)"
  
  post_build:
    commands:
      - echo "===== Creating zip archive ====="
      - cd dist
      - zip -r ../dist.zip .
      - cd ..
      - ls -lh dist.zip
      
      - echo "===== Uploading to S3 ====="
      - |
        if [ -z "$S3_BUCKET_NAME" ]; then
          echo "ERROR: S3_BUCKET_NAME not set"
          exit 1
        fi
      - aws s3 cp dist.zip s3://$S3_BUCKET_NAME/dist.zip
      - echo "===== Upload Completed ====="
      - echo "File available at: https://$S3_BUCKET_NAME.s3.amazonaws.com/dist.zip"

artifacts:
  files:
    - dist.zip
  name: frontend-build-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - 'node_modules/**/*'