version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "===== Environment Check ====="
      - pwd
      - ls -la
      - echo "===== Installing Dependencies ====="
      - npm install --legacy-peer-deps
  
  build:
    commands:
      - echo "===== Building Application ====="
      - npm run build
      - ls -la dist/
  
  post_build:
    commands:
      - echo "===== S3 Deployment ====="
      - echo "Bucket: $S3_BUCKET_NAME"
      - |
        if [ -z "$S3_BUCKET_NAME" ]; then
          echo "ERROR: S3_BUCKET_NAME not set"
          exit 1
        fi
      - aws s3 sync dist s3://$S3_BUCKET_NAME --delete
      - echo "Deployment completed"

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - 'node_modules/**/*'