version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Moving to Frontend directory...
      - cd Frontend
      - echo Installing dependencies...
      - npm install
  
  build:
    commands:
      - echo Building application...
      - cd Frontend
      - npm run build
      - echo Checking build output...
      - ls -la dist/
  
  post_build:
    commands:
      - echo Current directory before sync...
      - pwd
      - ls -la
      - echo Syncing Frontend/dist to S3...
      - aws s3 sync Frontend/dist s3://$S3_BUCKET_NAME --delete
      - echo Sync completed successfully

artifacts:
  files:
    - '**/*'
  base-directory: Frontend/dist

cache:
  paths:
    - 'Frontend/node_modules/**/*'