version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - |
        echo "===== Environment Info ====="
        node --version
        npm --version
        pwd
        ls -la
        echo "===== Installing Dependencies ====="
        npm install --legacy-peer-deps
  
  build:
    commands:
      - |
        echo "===== Building Application ====="
        npm run build
        echo "===== Build Summary ====="
        du -sh dist
        find dist -type f | wc -l
        ls -la dist/
  
  post_build:
    commands:
      - |
        if [ -z "$S3_BUCKET_NAME" ]; then
          echo "ERROR: S3_BUCKET_NAME environment variable not set"
          exit 1
        fi
        
        BUILD_TIME=$(date +%Y%m%d-%H%M%S)
        COMMIT_HASH=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION:-unknown} | cut -c1-7)
        
        echo "Build Time: $BUILD_TIME"
        echo "Commit: $COMMIT_HASH"
        
        echo "===== Creating Archive ====="
        cd dist
        zip -r ../dist-${BUILD_TIME}.zip .
        cd ..
        
        echo "Archive size:"
        ls -lh dist-${BUILD_TIME}.zip
        
        echo "===== Uploading to S3 ====="
        echo "Target bucket: $S3_BUCKET_NAME"
        
        aws s3 cp dist-${BUILD_TIME}.zip s3://$S3_BUCKET_NAME/releases/dist-${BUILD_TIME}.zip
        aws s3 cp dist-${BUILD_TIME}.zip s3://$S3_BUCKET_NAME/dist-latest.zip
        
        echo ""
        echo "===== Deployment Completed ====="
        echo "Latest: https://$S3_BUCKET_NAME.s3.amazonaws.com/dist-latest.zip"
        echo "Archive: https://$S3_BUCKET_NAME.s3.amazonaws.com/releases/dist-${BUILD_TIME}.zip"

cache:
  paths:
    - 'node_modules/**/*'