version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "===== Node.js Version ====="
      - node --version
      - npm --version
      - echo "===== Current Directory ====="
      - pwd
      - ls -la
      - echo "===== Installing Dependencies ====="
      - npm install --legacy-peer-deps
  
  build:
    commands:
      - echo "===== Building Application ====="
      - npm run build
      - echo "===== Build Output ====="
      - ls -la dist/
      - echo "Total files - $(find dist -type f | wc -l)"
  
  post_build:
    commands:
      - echo "===== Checking S3 Configuration ====="
      - echo "S3_BUCKET_NAME = $S3_BUCKET_NAME"
      - |
        if [ -z "$S3_BUCKET_NAME" ]; then
          echo "ERROR: S3_BUCKET_NAME environment variable not set"
          echo "Please set it in CodeBuild project environment variables"
          exit 1
        fi
      - echo "===== Syncing to S3 ====="
      - aws s3 sync dist s3://$S3_BUCKET_NAME --delete --cache-control "max-age=31536000,public" --exclude "*.html"
      - aws s3 cp dist/index.html s3://$S3_BUCKET_NAME/index.html --cache-control "max-age=0,no-cache,no-store,must-revalidate"
      - echo "===== Deployment Completed ====="
      - aws s3 ls s3://$S3_BUCKET_NAME/ --recursive --human-readable --summarize | tail -3

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - 'node_modules/**/*'