version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - |
        echo "===== Environment Check ====="
        pwd
        ls -la
        echo ""
        echo "===== Moving to Frontend ====="
        cd Frontend || { echo "Failed to cd into Frontend"; exit 1; }
        pwd
        ls -la
        echo ""
        echo "===== Installing Dependencies ====="
        npm install --legacy-peer-deps
  
  build:
    commands:
      - |
        cd Frontend
        echo "===== Building Application ====="
        npm run build
        echo ""
        echo "===== Build Output ====="
        ls -la dist/
        echo "Total files: $(find dist -type f | wc -l)"
  
  post_build:
    commands:
      - |
        echo "===== S3 Deployment ====="
        echo "Target bucket: $S3_BUCKET_NAME"
        if [ -z "$S3_BUCKET_NAME" ]; then
          echo "ERROR: S3_BUCKET_NAME environment variable not set"
          exit 1
        fi
        echo "Syncing files to S3..."
        cd dist
        aws s3 sync . s3://$S3_BUCKET_NAME --delete --cache-control "max-age=31536000,public" --exclude "*.html"
        aws s3 cp index.html s3://$S3_BUCKET_NAME/index.html --cache-control "max-age=0,no-cache,no-store,must-revalidate"
        echo "===== Deployment Completed ====="
        aws s3 ls s3://$S3_BUCKET_NAME/ --recursive --human-readable --summarize | tail -3

artifacts:
  files:
    - '**/*'
  base-directory: Frontend/dist

cache:
  paths:
    - 'Frontend/node_modules/**/*'